package com.yuan.looker.model

data class Content(
    val alias: String,
    val boardid: String,
    val cid: String,
    val daynum: String,
    val digest: String,
    val docid: String,
    val downTimes: Int,
    val ename: String,
    val extraShowFields: String,
    val hasCover: Boolean,
    val imgsrc: String,
    val lmodify: String,
    val ltitle: String,
    val mtime: String,
    val order: Int,
    val postid: String,
    val priority: Int,
    val ptime: String,
    val quality: Int,
    val replyCount: Int,
    val riskLevel: Int,
    val source: String,
    val sourceId: String,
    val subtitle: String,
    val template: String,
    val title: String,
    val tname: String,
    val topic_background: String,
    val topicid: String,
    val upTimes: Int,
    val url: String,
    val url_3w: String,
    val votecount: Int
)